#.travis.yml
language: node_js
node_js:
  - "13.8.0"
branches:
  only:
    - master
    - dev
before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
script:
  - ng build --prod
deploy:
  - provider: firebase
    token: $FIREBASE_TOKEN
    project: test-angular-firebase-e3db2
    on:
      branch: master
      tags: true
#after_success:
#  - test $TRAVIS_BRANCH = "master" && echo master && firebase deploy --token $FIREBASE_TOKEN --only hosting:test-angular-firebase-e3db2
#  - test $TRAVIS_BRANCH = "dev" && echo dev && firebase deploy --token $FIREBASE_TOKEN --only hosting:beta-test-angular-firebase
notifications:
  email:
    recipients:
      $NOTIFICATION_EMAIL
    on_failure: always
    on_success: always
